---
spring:
  resources.static-locations: "file:./app"  # for fast UI-dev turnarounds
cds:
  odatav4.endpoint.path: "/api"

---
spring:
  profiles: cloud

---
spring:
  profiles: sqlite
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1